### ISSUE TITLE
Request: prebuilt binaries for 32-bit arm on Linux

### ISSUE THREAD

**Issue by m040601** [Jacalz/wormhole-gui#13]
Wormhole, and especially it's go implementation runs perfectly fine in a plethora of **very popular** and diferent arm architectures, such as the different Raspberry Pi's version and a lot of Chromebooks **that are not arm64**.

Currently, wormhole-gui, only builds for arm64, that is, for ex: the Raspberry Pi 4. That leaves out, for ex:

- Raspberry Pi Zero : armv6
- Raspberry Pi 2 : armv7

Since with Github automations the cost of building for these other arms is the same. Wormhole-william itself, https://github.com/psanford/wormhole-william/releases does it. As well as almost every other go project.

So I would like to request this for wormhole-gui as well.

Thanks in advance

**Comment by Jacalz** [comment]
Hmm, maybe. I need to think some more about it before making a decision.

The point about GitHub automation does not quite apply as I'm not using it for cross-compiling the builds. The fyne gui toolkit requires CGO, so I'm using [fyne-cross](https://github.com/fyne-io/fyne-cross) for the builds, which adds some overhead to the whole process. I am planning to add `FreeBSD/arm64` and `Windows/arm64` in the future and I'm not so certain that I want to flood the releases with two or three more Linux binaries. My opinion is also kind of that 32-bit is dying.

**Comment by Jacalz** [comment]
> As well as almost every other go project.

Do you have a source for that? I believe that I pretty much never have seen any other Go project having specific binaries for multiple arm versions. Most of them don't even have ones for arm64 from what I have seen.

**Comment by m040601** [comment]
> I believe that I pretty much never have seen any other Go project having specific binaries for multiple arm versions.


https://github.com/psanford/wormhole-william/releases/
https://github.com/schollz/croc/releases/

https://github.com/junegunn/fzf/releases/
https://github.com/gokcehan/lf/releases
https://github.com/syncthing/syncthing/releases
https://github.com/gohugoio/hugo/releases

**Comment by Jacalz** [comment]
Yes, I know that fyne-cross supports 32-bit arm. I just meant that it wasn't quite as automated.

> For most not super complicated apps you usually just need 2 arm's. One for arm 64, that you have already. And one, simply called "arm" that will default to the simple 32 bit arm possible, and be compatible with the other 32 arm.

Ah, sorry. I thought you were saying that I should have arm-v4, arm-v5, arm-v6 and so on. That makes things a lot simpler.

**Comment by Jacalz** [comment]
I have decided to not go forward with this for the time being. The next release will have binaries for `freebsd/arm64` and `darwin/arm64` available and for that reason I don't want the overhead of making build times even with having to compile for a 32-bit architecture. I could reconsider this if more people show their interest, but at this current time, I will not go forward with this. I am sorry.
