### ISSUE TITLE
readme mentions local-network only

### ISSUE THREAD

**Issue by hamoid** [Jacalz/wormhole-gui#14]
Is wormhole-gui local network only? I have used wormhole across the internet...

**Comment by Jacalz** [comment]
Believe it or not, I had actually never had any use case for using it outside my local network and thus had not tried it. As I did not want to advertise something that I didn't know if it worked, I never got around to changing the wording. Thanks for notifying me :)

**Comment by Jacalz** [comment]
Fixed now :)

**Comment by hamoid** [comment]
Why send e-mails to geeky friends when you can send wormholes? :-P

**Comment by Jacalz** [comment]
Hehe. Good question 😝
