### ISSUE TITLE
GUI hidden when running on a VirtualBox Windows VM

### ISSUE THREAD

**Issue by StrangePeanut** [Jacalz/wormhole-gui#15]
### Description:
No GUI shown when running on a VirtualBox Windows VM. The process can be seen running in the background in Task Manager.

### Steps to Reproduce:
1. Run Wormhole

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 20H2
 - **Go version:** n/a
 - **Wormhole-gui version:** 2.2.0

**Comment by Jacalz** [comment]
Thanks for opening this issue. I think your virtual machine is lacking gpu acceleration and thus is the culprit here. Could you please try to apply the method mentioned in this comment https://github.com/fyne-io/fyne/issues/2046#issuecomment-787485932?

**Comment by StrangePeanut** [comment]
Thanks, enabling GPU acceleration solves the issue for Wormhole, but it also makes the VM run very poorly, rendering it completely unusable sometimes. Windows guests also require a minimum of 128MB video memory for it to work in the first place. It’s a pity Wormhole cannot be used without GPU acceleration.

**Comment by Jacalz** [comment]
Thanks for confirming that it works with GPU acceleration and banked. I'll close this as I don't think there is anything that I can do about it, unfortunately.
