### ISSUE TITLE
Does not display file name until fully downloaded

### ISSUE THREAD

**Issue by dhouck** [Jacalz/wormhole-gui#17]
### Description:

When receiving a file, the program says Waiting for Filename during the entire download process, at least when the sending user is using the Python wormhole implementation.  In contrast, the Python package shows the filename before downloading any of the file.

### Steps to Reproduce:

1. Using the Python magic-wormhole package, send a large file (`wormhole send large-file`)
2. Using wormhole-gui, enter the given code and hit Download
3. Note that the status is Waiting for Filename the entire time, although once transfer is complete the file name shows up correctly.

### Screenshots:

![image](https://user-images.githubusercontent.com/524925/126723037-1d9ba9a4-567b-4230-bce9-abcfcc6d962b.png)

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **Go version:** Unknown
 - **Wormhole-gui version:** 2.2.2
 - **Sending program version:** magic-wormhole 0.12.0

**Comment by Jacalz** [comment]
Hmm, I release that this might be an inconvenience and be especially annoying with large files. However, with the current implementation of the file icons, I don’t think it’s possible to fix this without a major overhaul of the code. I have a possible hotfix in mind that I’ll have to try when I have some time over, but I have no idea if it is going to work or not.

**Comment by Jacalz** [comment]
The fix was not as hard as I thought it would be. Fix will be in the next release :)
