### ISSUE TITLE
Add support for recipient verification

### ISSUE THREAD

**Issue by dhouck** [Jacalz/wormhole-gui#18]
### Is your feature request related to a problem? Please describe:

Other wormhole implementations, including the Python magic-wormhole and the wormhole-william package used by wormhole-gui, support a verification option so the sender can make sure they have the right recipient.  This doesnʼt seem to be an option in wormhole-gui

### Describe the solution you'd like to see:

Support this feature, perhaps with a checkbox on the send and receive page for whether to include it, and a dialog to display the verification code.

**Comment by Jacalz** [comment]
This is a great suggestion. Thanks for the feature request. I’ll make sure that it will land in the next big release (will most likely be a small release in between).

**Comment by Jacalz** [comment]
Initial support for this is now added with https://github.com/Jacalz/wormhole-gui/commit/4986c14a8d2d9955a422dca572184c49a220cd79 on the "verify" branch. Feel free to compile locally and test if you want. This will not be included in the next release unfortunately as text wrapping isn't working in dialogs at the moment, see https://github.com/fyne-io/fyne/pull/1001.

**Comment by Jacalz** [comment]
Sorry that this took such a long time. I had another look at this and realised that my old code was terrible. This should work a lot better than that and and be in the next release :)
