### ISSUE TITLE
Progress bar stuck at 0% after text message has been received

### ISSUE THREAD

**Issue by moppman** [Jacalz/wormhole-gui#2]
First of all, nice project! This could be really useful for people to get to know wormhole.
You're probably already aware of my issue here:
1. Pick "Send" mode
2. Click "Add content to send"
3. Pick "Text"
4. Enter message and hit "Send"
5. Other party enters code on their client to receive message.
6. Message is received.

**Expected:**
7. Progress bar on sender's side for the "Text Snippet" is at 100% to mark success, just like for sending files.

**Actual:**
7. Progress bar on sender's side for the "Text Snippet" persists at 0% with no indication that the message has been sent successfully.

This is probably due to text messages being handled as "kind of" files. 
Imho, a dedicated text message option is not really necessary here, although the wormhole API of course makes that distinction. But I think people use other stuff for messages anyway :).
Plus, by removing the text option, you could get rid of the "Pick a content type" menu and jump straight to the file picker dialog.
Thanks for reading!

**Comment by Jacalz** [comment]
Thank you for the kind words and thanks for opening the issue. Will make sure to get it into the next release soon :)

**Comment by Jacalz** [comment]
I just pushed a new release with this fix in it: https://github.com/Jacalz/wormhole-gui/releases/tag/v1.3.0
