### ISSUE TITLE
Show % progress recipient side (not only sender side)

### ISSUE THREAD

**Issue by BackSpace54** [Jacalz/wormhole-gui#20]
Hi,
as the CLI version and the sender side in the GUI version display it, could you show the % progress for the receiver side and not only a looping progress bar?
Tia.

**Comment by BackSpace54** [comment]
Hi,
regular wormhole-william cli show progress bar, %, transfert speed and ETA on both side :
![wormhole-william-windows](https://user-images.githubusercontent.com/57332400/129102533-aa6044ff-d2d7-4964-996d-45945235e3e7.png)
Thanks for what you can do.

**Comment by Jacalz** [comment]
Thanks for confirming. I’ll dig into tit when I have some time to do so :)

**Comment by Jacalz** [comment]
The plan is to have this in the next big release. It is quite a hard feature to implement as it requires a lot of changes to the code to be able to do properly.

**Comment by Jacalz** [comment]
I came up with a much better solution and it turned out to be much less hard to fix than I thought. Thanks a lot for the suggestion. Should be fixed now on master now :)
