### ISSUE TITLE
Windows defender is saying it contains virus or potentially unwanted software

### ISSUE THREAD

**Issue by millersc454** [Jacalz/wormhole-gui#21]
### Steps to Reproduce:

1. This is triggered when extracting the file.
2. 
3. 

### Device (please complete the following information):
 - **OS:** 
 - **Version:** 
 - **Go version:** 
 - **Wormhole-gui version:**

**Comment by Jacalz** [comment]
In the future, please fill out the entire issue template, but it’s fine in this case. As for the issue, there is a very fine line here. Are you sure that it says that it “contains” an that it not “may contain”?  What it most likely is saying, is that it may contain because the binary isn’t signed and they can’t thus know that it is to be trusted.

The only solution for this would be to sign the binaries so that the anti virus know that they are to be trusted. It has unfortunately been held back due to funding and time constraints.

**Comment by millersc454** [comment]
Jacob, I don’t believe there’s a problem.  I think windows 10 just thinks there is.  But, I didn’t want to risk it, until I asked you.

 

I attached some screenshots.

 

V/R

 

Steve

**Comment by katchy3132** [comment]
I get this error too from Kaspersky. Currently on 2.3 but I got it on 2.2 as well 

![image](https://user-images.githubusercontent.com/3707138/132104855-a633a70b-9960-456c-8730-100600d92385.png)

**Comment by katchy3132** [comment]
this too 
![image](https://user-images.githubusercontent.com/3707138/132105029-d270b98d-2f86-4655-9479-2065701a29b9.png)

**Comment by katchy3132** [comment]
flagged by 8 vendors on virustotal 

https://www.virustotal.com/gui/file/174c161252dfe50459527f25da46e579a5e1e4a069b9dff87f17cc1259476d66/detection

**Comment by Jacalz** [comment]
That is very strange. I hope that it just is a false positive, but I promise to look into it. I don't know why this would be happening.

**Comment by Jacalz** [comment]
I don't know what happened. I have removed all of the release binaries from the previous release and created a new release and made sure that the git tag is properly GPG-signed now. The new release can be found here: https://github.com/Jacalz/wormhole-gui/releases/tag/v2.3.1

https://www.virustotal.com/gui/file/78de56dc2ba0c62898f6a422e86ca2420c5deb3bfc934b733d8379cec7e58902/detection

**Comment by katchy3132** [comment]
FYI there are now 4 flags (including Kaspersky )

**Comment by Jacalz** [comment]
I really don't understand why this is happening...

**Comment by Jacalz** [comment]
I will have to dig through the changes between 2.2.0 and 2.3.0 to see if there is some code change that triggers the anti virus softwares to report it as malware. I have checked my account, changed password (just to be on the safe side, already had 2FA + long randomly generated password) with nothing pointing to my account having been breached. I highly doubt that the binaries would have been infected for real two times in a row. I'm honestly very confused about why this is happening. Any help would be appreciated.

**Comment by Jacalz** [comment]
Found the source of the issue. Looks to not be infected binaries, just as I assumed. Will work to get this fixed.

**Comment by Jacalz** [comment]
The re-released v2.3.1 are no longer flagged after updating the dep. Closing.

**Comment by NESS-Network** [comment]
the false-positive Windows Defender came back. Win10 x64

<img width="512" height="963" alt="Image" src="https://github.com/user-attachments/assets/089598bb-25dc-4709-9fe7-b7b9509d0dd0" />

**Comment by Jeff-Bouchard** [comment]
this issue just came back, with brave on windows 10 fully patched

**Comment by Jacalz** [comment]
That's unfortunate. I don't think there is much I can do about it unfortunately. Windows is such a mess :/
