### ISSUE TITLE
Very long filenames can cause UI issues

### ISSUE THREAD

**Issue by nfd9001** [Jacalz/wormhole-gui#24]
### Description:

Trying to send files with long filenames can cause the wormhole code and progress bars to fall off the right side of the screen.
I expected the filename to truncate (possibly with a hover tooltip to display the whole thing). (A frend I asked to try wormhole-gui out *did* try to send me a document with a large filename and couldn't figure out what to do as a result: it wasn't even obvious that there was *supposed* to be more detail to the right.)

### Screenshots:

![image](https://user-images.githubusercontent.com/5666174/135521398-8d4d3a72-afda-471b-a808-67d6d0711664.png)

### Device (please complete the following information):
Tested on Windows, Arch Linux, both v. 2.3.1

**Comment by Jacalz** [comment]
Thanks for opening this issue. The problem has actually already been resolved by https://github.com/Jacalz/wormhole-gui/commit/5203f6418d23ca1acee36fda8e7d2c895251a42c and should be in the next release.

**Comment by Jacalz** [comment]
I will close this given the comment above. Thanks for notifying :)
