### ISSUE TITLE
Apple M1 users getting error "wormhole-gui" is damaged and can't be opened

### ISSUE THREAD

**Issue by vlasky** [Jacalz/wormhole-gui#27]
I tried to send files to two different colleagues who each have Apple Macbook Pro M1 laptops. I got them to download and decompress [the latest 2.3.1 build for macOS-arm64](https://github.com/Jacalz/wormhole-gui/releases/download/v2.3.1/wormhole-gui-v2.3.1-macOS-arm64.zip).

When they attempted to run program they both got the following error:

<img width="368" alt="wormhole-gui-2 3 1-error-screenshot" src="https://user-images.githubusercontent.com/12727610/140441198-4b236259-dbc7-4d02-be6c-ea77e8961937.png">

**Comment by Jacalz** [comment]
Thanks for notifying me. I'm looking into it.

**Comment by Jacalz** [comment]
So they have the Gatekeeper setting turned off to allow unverified binaries to run? I know that it's unfortunate, but it's what I can get at the moment. There is a not about it here: https://github.com/Jacalz/wormhole-gui/releases/tag/v2.3.0.

I really should have added that note to the latest release as well or make it more findable.

**Comment by Jacalz** [comment]
Do you think you could ask them to try and run the binary from the Console? I am not entirely familiar with macOS but I think you run `.app` using the `open` command followed by the binary name/path.

We should hopefully get some useful information that can point us in the right direction.

**Comment by Jacalz** [comment]
Ping @vlasky per questions above.

**Comment by Jacalz** [comment]
This is very important information given that I don't have any local access to M1 machines. However, they should be able to use the amd64 binaries through rosetta2 in the meantime.

**Comment by Jacalz** [comment]
Closing due to lack of response. Feel free to reopen if you have more information.

**Comment by Jacalz** [comment]
This should now be solved with https://github.com/Jacalz/rymdport/commit/b6979ac486088521d600168efc7946d40c7b8a8a. Sorry for this not working entirely correct before :/
