### ISSUE TITLE
Windows build fails

### ISSUE THREAD

**Issue by asakura42** [Jacalz/wormhole-gui#29]
### Description:

Error when I try to build it in Win10:

```
$ go build
# github.com/go-gl/gl/v3.2-core/gl
gcc.exe: fatal error: cannot execute 'as': CreateProcess: No such file or directory
compilation terminated.
# github.com/go-gl/glfw/v3.3/glfw
gcc.exe: fatal error: cannot execute 'as': CreateProcess: No such file or directory
compilation terminated.
```

Are that `gl` and `glfw` issues?

Also, go and gcc installed with `scoop`

### Device (please complete the following information):
 - **OS:**  Windows
 - **Version:** 10
 - **Go version:** 1.17.5
 - **Wormhole-gui version:** https://github.com/Jacalz/wormhole-gui/commit/6cc27e7e0c225f05d8a2a60ddefc4591614d81f8

**Comment by Jacalz** [comment]
Hmm, I think you are right that it technically isn't a problem with this project. It almost sounds like here is some compile dependency is missing on your system. Missing the mingw toolchain? I am not familiar with scoop, so I think I'd suggest following the install-steps over at https://developer.fyne.io/started/ instead (unless you manage to figure it out using scoop).

I'm sorry if this answer wasn't much help. I'm mainly a Linux developer and only use Windows when I really need to.

**Comment by Jacalz** [comment]
Looking again, it looks like some `as` command is missing. I have no idea what would provide that on Windows.

**Comment by asakura42** [comment]
> Hmm, I think you are right that it technically isn't a problem with this project. It almost sounds like here is some compile dependency is missing on your system. Missing the mingw toolchain? I am not familiar with scoop, so I think I'd suggest following the install-steps over at https://developer.fyne.io/started/ instead (unless you manage to figure it out using scoop).
> 
> I'm sorry if this answer wasn't much help. I'm mainly a Linux developer and only use Windows when I really need to.

Not a Win-user too, but my family are. Your prebuild binary detects as Trojan, so I thought self-building can fix this problem. But maybe I just can cross-compile it.

**Comment by asakura42** [comment]
https://www.virustotal.com/gui/file/07d58ec83fb74fdf160e3d23241e12854a02d5e31977551e4db75a488b055eb9 - about Trojan

**Comment by Jacalz** [comment]
I know about the false-positive where it is reported as a trojan. Compiling locally on Windows is unfortunately not going to solve anything as something with klauspost/compress (a very well-known and widely used package for performant archive algorithms) makes those four virus scanners freak out. I suggest that you have a look at https://github.com/klauspost/compress/issues/440.

**Comment by gedw99** [comment]
Did you try garbling the code. I had the same problem using it with gio and it works.

**Comment by Jacalz** [comment]
I nerver did. It felt a bit like an ugly workaround and I didn't know if it would be worth it. Might have to do it only for Windows though. Thanks for bringing up the suggestion again.

**Comment by Jacalz** [comment]
Does I make more sense to open an issue for `scoop` instead? There is clearly something that hasn’t been installed correctly. I honestly don’t think that there is more I can do to help here unfortunately :/

**Comment by gedw99** [comment]
> I nerver did. It felt a bit like an ugly workaround and I didn't know if it would be worth it. Might have to do it only for Windows though. Thanks for bringing up the suggestion again.

If it’s useful I can say that it was very easy and took 5 minutes to do. So worth a try maybe .

https://github.com/burrowers/garble

**Comment by Jacalz** [comment]
That won't work because of a few reasons. The first one, and biggest issue, is that I cross-compile using https://github.com/fyne-io/fyne-cross for the compilation and I can't just tell it to use that when building. The second is that I just have Go 1.16 locally because someone working with Fedora Linux forgot to get Go 1.17 into Fedora 35. The third issue is that I just don't like the idea of having to that. To be fair, it is their crappy malware scanners that are the issue here, not my code.

I think the only sensible solution for me is to get the windows binaries signed and/or add it to the Windows store. The latter is a bit annoying since I need a Windows computer, but that's probably easy enough to solve. The largest issue with these two are currently funding though.

**Comment by gedw99** [comment]
Yeah right I get ya.

You can sign it on windows using GitHub CI. So you don’t need a windows computer or van.
It’s what I do.

Also for desktop you can sign for free using gatekeeper.


I had no idea that signing the binary means that a virus scanner  lets it through, as opposed to unsigned binary.

**Comment by Jacalz** [comment]
> I had no idea that signing the binary means that a virus scanner  lets it through, as opposed to unsigned binary.

It probably doesn't, but I meant using a an official signing certificate from Microsoft. In other words, having me as a verified developer.

**Comment by Jacalz** [comment]
> Does I make more sense to open an issue for `scoop` instead? It looks like there is something that hasn't been installed and thus is missing on the system. I honestly don’t think that there is more I can do to help here other than to suggest following https://developer.fyne.io/started/ for installing compile dependencies.

I will close this per the comment above, but feel free to open more issues if you find any issues that needs to be fixed.
