### ISSUE TITLE
[Suggestion] Use "copy" button instead of right-click menu for copying the magic code

### ISSUE THREAD

**Issue by moppman** [Jacalz/wormhole-gui#3]
Thanks for solving #2 so quickly, great work!
I was just trying out v1.3.0 and I like the "Copy to clipboard" and "Save to file" options after receiving a text message a lot.
And that reminded me of a minor quibble I had with your app:

- The magic wormhole code that's displayed after sending is not copyable. Or so I thought :)
- Looking at the code, I noticed we can use a right-click to copy the code to the clipboard. 
- Because there is no visual indication that the code is copyable this way and because you don't use a right-click menu anywhere else in the app afaik, maybe put a little widget next to the code instead of the right-click menu, like you do [here](https://github.com/Jacalz/wormhole-gui/commit/31770283929997685a0b1de8caab6ad6cedbe3c0#diff-f215e5ddadc19e6cd03c3c54e7771821R19) ?
Thanks!

**Comment by Jacalz** [comment]
Good idea. It definitely needs to be more findable. I might tackle this after fyne 1.4 is released with a fancy new list widget that might make the whole list of sent items look a bit better.

**Comment by Jacalz** [comment]
Here is a little sneak-peek of what is cooking in the `develop` branch ahead of the 2.0 release:
![sneak-peek-wormhole-gui-2 0](https://user-images.githubusercontent.com/25466657/93755634-ef69a100-fc03-11ea-8bd5-21a00cc512f9.gif)

**Comment by Jacalz** [comment]
An improved version with file extensions is now available in the `develop` branch. Going to close this now :)
![image](https://user-images.githubusercontent.com/25466657/95247553-4d0e0800-0816-11eb-92cc-f565a4c43dcd.png)

**Comment by moppman** [comment]
I just checked the dev branch: nice work!!

**Comment by Jacalz** [comment]
Thank you :)

**Comment by Jacalz** [comment]
This is now included as part of the 2.0.0 release. https://github.com/Jacalz/wormhole-gui/releases/tag/v2.0.0
