### ISSUE TITLE
Can't change PassPhrase Length via GUI

### ISSUE THREAD

**Issue by glitsj16** [Jacalz/wormhole-gui#31]
### Description:

Installed the [AUR package](https://aur.archlinux.org/packages/wormhole-gui-bin) today. I noticed that the slider for setting `PassPhrase Length` is broken: it can't be selected by tabbing, nor by clicking. Manually editing ~/.config/fyne/com.github.jacalz.wormhole-gui/preferences.json does work.

### Steps to Reproduce:

1. Open 'Settings'
2. Go to 'Wormhole Options'
3. Try to move the 'PassPhrase Length' slider

### Device (please complete the following information):
 - **OS:**  Arch Linux
 - **Version:**  rolling relase
 - **Go version:**  go version go1.17.7 linux/amd64
 - **Wormhole-gui version:**  2.3.1

**Comment by Jacalz** [comment]
Hmm, this sounds very strange. It's not something that I have seen before. To be sure, I downloaded the same release binary from the same release and ran it in my Fedora machine, but I couldn't replicate it.

Are you sure that you are dragging the mouse far enough? The steps on the slider are relatively large, so you'll have to move the mouse quite a lot. The slider also doesn't show any indication that it is selected when you press the mouse on it. I suspect one of these issues could be the culprit?

**Comment by glitsj16** [comment]
> Are you sure that you are dragging the mouse far enough?

That's the thing I'm seeing this on a laptop with only a touchpad :-). I just borrowed a USB mouse and indeed, that can move the slider.

Thank you for your response and looking into this. Feel free to close this issue, I have the setting I prefer and can always change the preferences file directly.

Regards!

**Comment by Jacalz** [comment]
You're welcome. Thanks for opening the issue. I'll make sure that we can get the slider widget focusable in the future. However, it should work fine on touchpads as-is though. I only meant that you had to move the mouse pointer. Is there no enough space to drag it on the touchpad? I'm using it on my touchpad without issues.

**Comment by glitsj16** [comment]
Aha, your last comment triggered my brain cell. The touchpad on this (12y old) laptop is showing issues that I had to work around with a custom ~/.Xmodmap. Most likely that is the culprit.

**Comment by Jacalz** [comment]
Ah, I see. Thanks for the information. I'll go ahead and close this then.
