### ISSUE TITLE
How to setup with custom/self-hosted Wormhole server?

### ISSUE THREAD

**Issue by Darthagnon** [Jacalz/wormhole-gui#9]
### Is your feature request related to a problem? Please describe:
Magic Wormhole has a [main server](https://github.com/magic-wormhole/magic-wormhole-mailbox-server) and [relay server](https://github.com/magic-wormhole/magic-wormhole-transit-relay) that can be self-hosted. If users have privacy concerns, or just want to host it all themselves, so as not to use the official Magic Wormhole servers run by the project maintainers, they can do so...

### Describe the solution you'd like to see:
... but there is no apparent way to connect to custom/self-hosted Magic Wormhole servers in the GUI/settings for this project. Would it be possible to add "Custom Server Address" under ```Settings``` >> ```Wormhole Options```?

**Comment by Darthagnon** [comment]
Thank you so much!!! ❤❤❤

**Comment by Jacalz** [comment]
How about this? I hooked up all the missing client values and put it under an advanced section.
![image](https://user-images.githubusercontent.com/25466657/108877197-4b937f80-75ff-11eb-8383-77b13053639b.png)

**Comment by Jacalz** [comment]
Forgot to mention that the code for doing that is up on the `develop` branch as of commit https://github.com/Jacalz/wormhole-gui/commit/06a1a588d73f1dab3eccdeac4e5145e36a09d800. There might be a bug fix release (version 2.1.1) landing in a few weeks, but this should be in the v2.2.0 release.

If you want to test, you can build from source on the mentioned branch. If you don’t want to build from source, I can spin up a few test binaries for your preferred platform?

**Comment by Jacalz** [comment]
I'll close this now as it will be in the next release (v2.2.0). Should be releasing in a week or two hopefully.

**Comment by Darthagnon** [comment]
Thank you so much, Jacalz! 

I had tested from a (semi-successful) build I managed to do, and am really happy that it's now in the main release!

**Comment by Jacalz** [comment]
You're very welcome. I'm glad you liked it 🙂
